### ISSUE TITLE
 ReferenceError: location is not defined

### ISSUE THREAD

**Issue by bartekfigat** [bartekfigat/MERN_weather_app#1]
trying to save the newWeather object to MongoDb, but without success, 
in console.log I have this err: (node:21296) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ReferenceError: location is not defined

**Comment by Nevo0** [comment]
City was undefined, answer from the server: "CW: City Information Required for product type::local_conditions'"
i fix issue 
in 
> MERN_weather_app\func\func.js
[https://github.com/bartekfigat/MERN_weather_app/blob/playground/func/func.js](url)

change

`const city = req.body.user.city;`
